# config grpc-server & retranlator

project:
  name: Logistic Package API
  debug: true
  allowRiseToDebug: false
  environment: development

#
# grpc-server service hosts:
grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

rest:
  host: 0.0.0.0
  port: 8080

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

#
# grpc-server service connects:
jaeger:
  tracing:
    logSpans: false
    rateLimiting: false # false = SamplerTypeConst
    spansPerSecond: 10
  service: "logistic-package-api"
  # host: "host.docker.internal"
  # host: "localhost"
  host: "jaeger"
  port: ":6831"

database:
  # host: host.docker.internal
  # host: localhost
  host: postgres

  port: 5432
  user: postgres
  password: postgres
  name: logistic_package_api
  sslmode: disable
  migrations: migrations
  driver: pgx
  connection:
    attempts: 15
    maxOpenConns: 5
    maxIdleConns: 5
    connMaxIdleTime: 300s
    connMaxLifetime: 300s

kafka:
  attempts: 5
  topic: "omp-package-events"
  brokers:
    # - "localhost:9094"
    # - "host.docker.internal:9094"
    - "kafka:9092"

#
# retranslator app config:
retranslator:
  metricsaddr: 0.0.0.0:9101
  metricspath: /metrics
  name: Logistic Package API retranslator
  debug: true
  enabled: true
  channelSize: 512
  consumerCount: 2
  batchSize: 5
  consumeInterval: 30s
  producerCount: 8
  workerCount: 2