# Builder

ARG GITHUB_PATH=github.com/hablof/logistic-package-api

FROM golang:1.19-alpine AS builder

WORKDIR /home/${GITHUB_PATH}

RUN apk add --update make git protoc protobuf protobuf-dev curl

COPY . .
RUN make build-server

# gRPC Server

FROM alpine:latest as server
LABEL org.opencontainers.image.source https://${GITHUB_PATH}
RUN apk --no-cache add ca-certificates
WORKDIR /root/

COPY --from=builder /home/${GITHUB_PATH}/bin/grpc-server .
# COPY --from=builder /home/${GITHUB_PATH}/config.yml .

RUN chown root:root grpc-server

EXPOSE 8000
EXPOSE 8080
EXPOSE 8082
EXPOSE 9100

CMD ["./grpc-server"]
