global:
  scrape_interval:     10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        # - host.docker.internal:9100
        # - host.docker.internal:9101
        
        - logistic-package-api:9100
        - logistic-package-api-retranslator:9101
