// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: hablof/logistic_package_api/v1/logistic_package_api.proto

/*
Package logistic_package_api is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package logistic_package_api

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_LogisticPackageApiService_DescribePackageV1_0(ctx context.Context, marshaler runtime.Marshaler, client LogisticPackageApiServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DescribePackageV1Request
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["package_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "package_id")
	}

	protoReq.PackageId, err = runtime.Uint64(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "package_id", err)
	}

	msg, err := client.DescribePackageV1(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_LogisticPackageApiService_DescribePackageV1_0(ctx context.Context, marshaler runtime.Marshaler, server LogisticPackageApiServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq DescribePackageV1Request
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["package_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "package_id")
	}

	protoReq.PackageId, err = runtime.Uint64(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "package_id", err)
	}

	msg, err := server.DescribePackageV1(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterLogisticPackageApiServiceHandlerServer registers the http handlers for service LogisticPackageApiService to "mux".
// UnaryRPC     :call LogisticPackageApiServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterLogisticPackageApiServiceHandlerFromEndpoint instead.
func RegisterLogisticPackageApiServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server LogisticPackageApiServiceServer) error {

	mux.Handle("GET", pattern_LogisticPackageApiService_DescribePackageV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/ozonmp.logistic_package_api.v1.LogisticPackageApiService/DescribePackageV1", runtime.WithHTTPPathPattern("/v1/packages/{package_id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_LogisticPackageApiService_DescribePackageV1_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_LogisticPackageApiService_DescribePackageV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterLogisticPackageApiServiceHandlerFromEndpoint is same as RegisterLogisticPackageApiServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterLogisticPackageApiServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterLogisticPackageApiServiceHandler(ctx, mux, conn)
}

// RegisterLogisticPackageApiServiceHandler registers the http handlers for service LogisticPackageApiService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterLogisticPackageApiServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterLogisticPackageApiServiceHandlerClient(ctx, mux, NewLogisticPackageApiServiceClient(conn))
}

// RegisterLogisticPackageApiServiceHandlerClient registers the http handlers for service LogisticPackageApiService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "LogisticPackageApiServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "LogisticPackageApiServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "LogisticPackageApiServiceClient" to call the correct interceptors.
func RegisterLogisticPackageApiServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client LogisticPackageApiServiceClient) error {

	mux.Handle("GET", pattern_LogisticPackageApiService_DescribePackageV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/ozonmp.logistic_package_api.v1.LogisticPackageApiService/DescribePackageV1", runtime.WithHTTPPathPattern("/v1/packages/{package_id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_LogisticPackageApiService_DescribePackageV1_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_LogisticPackageApiService_DescribePackageV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_LogisticPackageApiService_DescribePackageV1_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2}, []string{"v1", "packages", "package_id"}, ""))
)

var (
	forward_LogisticPackageApiService_DescribePackageV1_0 = runtime.ForwardResponseMessage
)
