// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: hablof/logistic_package_api/v1/logistic_package_api.proto

package logistic_package_api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
)

// Validate checks the field values on Package with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Package) Validate() error {
	if m == nil {
		return nil
	}

	// no validation rules for Id

	// no validation rules for Foo

	if v, ok := interface{}(m.GetCreated()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return PackageValidationError{
				field:  "Created",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// PackageValidationError is the validation error returned by Package.Validate
// if the designated constraints aren't met.
type PackageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PackageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PackageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PackageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PackageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PackageValidationError) ErrorName() string { return "PackageValidationError" }

// Error satisfies the builtin error interface
func (e PackageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPackage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PackageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PackageValidationError{}

// Validate checks the field values on DescribePackageV1Request with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribePackageV1Request) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetPackageId() <= 0 {
		return DescribePackageV1RequestValidationError{
			field:  "PackageId",
			reason: "value must be greater than 0",
		}
	}

	return nil
}

// DescribePackageV1RequestValidationError is the validation error returned by
// DescribePackageV1Request.Validate if the designated constraints aren't met.
type DescribePackageV1RequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribePackageV1RequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribePackageV1RequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribePackageV1RequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribePackageV1RequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribePackageV1RequestValidationError) ErrorName() string {
	return "DescribePackageV1RequestValidationError"
}

// Error satisfies the builtin error interface
func (e DescribePackageV1RequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribePackageV1Request.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribePackageV1RequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribePackageV1RequestValidationError{}

// Validate checks the field values on DescribePackageV1Response with the rules
// defined in the proto definition for this message. If any rules are
// violated, an error is returned.
func (m *DescribePackageV1Response) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetValue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DescribePackageV1ResponseValidationError{
				field:  "Value",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	return nil
}

// DescribePackageV1ResponseValidationError is the validation error returned by
// DescribePackageV1Response.Validate if the designated constraints aren't met.
type DescribePackageV1ResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DescribePackageV1ResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DescribePackageV1ResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DescribePackageV1ResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DescribePackageV1ResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DescribePackageV1ResponseValidationError) ErrorName() string {
	return "DescribePackageV1ResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DescribePackageV1ResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDescribePackageV1Response.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DescribePackageV1ResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DescribePackageV1ResponseValidationError{}
